# Generated by Django 3.0.2 on 2020-01-10 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('nothyP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon',
            new_name='region',
        ),
    ]
