# Generated by Django 3.0.2 on 2020-01-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nothyP', '0002_auto_20200110_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='region',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.ManyToManyField(to='nothyP.Region'),
        ),
    ]
